function typographyPreset(
  style,
  pairing,
  primaryFont,
  secondaryFont,
  scale,
  density,
  weight,
  headlineStyle,
  tightness,
) {
  return {
    density,
    headlineStyle,
    pairing,
    primaryFont,
    scale,
    secondaryFont,
    style,
    tightness,
    weight,
  };
}

export const TYPOGRAPHY_REMIX_PRESETS = [
  typographyPreset("geometric", "display_plus_text", "inter", "roboto", 72, 58, 64, 64, 54),
  typographyPreset("geometric", "display_plus_text", "space_grotesk", "dm_sans", 76, 56, 68, 72, 56),
  typographyPreset("geometric", "single_family", "sora", "sora", 74, 56, 76, 78, 58),
  typographyPreset("geometric", "mono_accent", "space_grotesk", "jetbrains_mono", 68, 52, 66, 70, 62),
  typographyPreset("grotesk", "display_plus_text", "helvetica_neue", "inter", 70, 58, 72, 66, 56),
  typographyPreset("grotesk", "display_plus_text", "work_sans", "open_sans", 66, 62, 58, 52, 48),
  typographyPreset("grotesk", "single_family", "helvetica_neue", "helvetica_neue", 66, 62, 58, 52, 48),
  typographyPreset("grotesk", "editorial_contrast", "georgia", "helvetica_neue", 82, 58, 50, 78, 70),
  typographyPreset("humanist", "single_family", "manrope", "manrope", 64, 68, 52, 46, 36),
  typographyPreset("humanist", "display_plus_text", "manrope", "karla", 68, 72, 48, 56, 30),
  typographyPreset("humanist", "display_plus_text", "raleway", "open_sans", 70, 64, 58, 60, 42),
  typographyPreset("humanist", "editorial_contrast", "lora", "manrope", 74, 66, 46, 64, 52),
  typographyPreset("editorial", "editorial_contrast", "georgia", "inter", 86, 54, 44, 88, 76),
  typographyPreset("editorial", "editorial_contrast", "playfair_display", "source_serif", 88, 58, 46, 90, 78),
  typographyPreset("editorial", "display_plus_text", "lora", "inter", 90, 60, 50, 80, 68),
  typographyPreset("editorial", "single_family", "merriweather", "merriweather", 78, 62, 48, 66, 46),
  typographyPreset("mono_tech", "mono_accent", "sf_mono", "inter", 58, 48, 56, 72, 64),
  typographyPreset("mono_tech", "mono_accent", "jetbrains_mono", "dm_sans", 60, 46, 62, 76, 70),
  typographyPreset("mono_tech", "display_plus_text", "fira_code", "inter", 62, 44, 62, 68, 70),
  typographyPreset("mono_tech", "single_family", "ibm_plex_mono", "ibm_plex_mono", 56, 42, 58, 62, 64),
  typographyPreset("playful", "display_plus_text", "nunito", "dm_sans", 78, 64, 70, 74, 42),
  typographyPreset("playful", "display_plus_text", "bebas_neue", "karla", 82, 58, 66, 88, 54),
  typographyPreset("playful", "single_family", "nunito", "nunito", 80, 66, 66, 62, 34),
  typographyPreset("playful", "editorial_contrast", "playfair_display", "nunito", 84, 62, 52, 82, 58),
  typographyPreset("luxury", "editorial_contrast", "didot", "manrope", 82, 50, 38, 92, 82),
  typographyPreset("luxury", "editorial_contrast", "bodoni_72", "manrope", 80, 52, 42, 90, 76),
  typographyPreset("luxury", "single_family", "didot", "didot", 76, 52, 42, 84, 74),
  typographyPreset("luxury", "display_plus_text", "libre_baskerville", "open_sans", 78, 56, 44, 78, 64),
  typographyPreset("geometric", "display_plus_text", "plus_jakarta_sans", "inter", 72, 58, 66, 68, 52),
  typographyPreset("geometric", "display_plus_text", "outfit", "source_sans_3", 76, 56, 70, 76, 58),
  typographyPreset("geometric", "display_plus_text", "urbanist", "manrope", 74, 58, 68, 70, 54),
  typographyPreset("geometric", "display_plus_text", "clash_display", "satoshi", 84, 54, 62, 88, 64),
  typographyPreset("geometric", "single_family", "plus_jakarta_sans", "plus_jakarta_sans", 70, 60, 62, 64, 48),
  typographyPreset("geometric", "single_family", "outfit", "outfit", 76, 58, 70, 76, 54),
  typographyPreset("geometric", "editorial_contrast", "fraunces", "dm_sans", 84, 60, 48, 84, 62),
  typographyPreset("geometric", "mono_accent", "sora", "space_mono", 70, 52, 66, 72, 64),
  typographyPreset("geometric", "mono_accent", "cabinet_grotesk", "commit_mono", 78, 50, 70, 82, 66),
  typographyPreset("grotesk", "display_plus_text", "satoshi", "inter", 70, 58, 64, 64, 50),
  typographyPreset("grotesk", "display_plus_text", "schibsted_grotesk", "source_sans_3", 70, 60, 64, 62, 48),
  typographyPreset("grotesk", "display_plus_text", "ibm_plex_sans", "public_sans", 66, 64, 56, 50, 42),
  typographyPreset("grotesk", "display_plus_text", "archivo", "barlow", 72, 56, 74, 72, 58),
  typographyPreset("grotesk", "single_family", "public_sans", "public_sans", 64, 66, 54, 48, 38),
  typographyPreset("grotesk", "single_family", "source_sans_3", "source_sans_3", 64, 68, 52, 46, 34),
  typographyPreset("grotesk", "editorial_contrast", "newsreader", "public_sans", 80, 62, 46, 76, 60),
  typographyPreset("grotesk", "mono_accent", "archivo", "roboto_mono", 70, 52, 72, 74, 66),
  typographyPreset("humanist", "display_plus_text", "atkinson_hyperlegible", "source_sans_3", 62, 74, 50, 44, 26),
  typographyPreset("humanist", "display_plus_text", "lexend", "nunito_sans", 66, 72, 54, 52, 30),
  typographyPreset("humanist", "display_plus_text", "assistant", "heebo", 66, 72, 50, 50, 32),
  typographyPreset("humanist", "single_family", "atkinson_hyperlegible", "atkinson_hyperlegible", 62, 76, 48, 42, 24),
  typographyPreset("humanist", "single_family", "lexend", "lexend", 64, 74, 52, 48, 28),
  typographyPreset("humanist", "editorial_contrast", "spectral", "source_sans_3", 76, 66, 46, 68, 54),
  typographyPreset("humanist", "editorial_contrast", "pt_serif", "noto_sans", 74, 68, 46, 64, 50),
  typographyPreset("humanist", "mono_accent", "assistant", "source_code_pro", 64, 60, 54, 54, 48),
  typographyPreset("editorial", "editorial_contrast", "eb_garamond", "source_sans_3", 86, 58, 42, 88, 76),
  typographyPreset("editorial", "editorial_contrast", "cormorant_garamond", "satoshi", 90, 54, 40, 92, 82),
  typographyPreset("editorial", "editorial_contrast", "newsreader", "inter", 84, 62, 46, 80, 66),
  typographyPreset("editorial", "editorial_contrast", "libre_caslon_text", "public_sans", 82, 60, 44, 76, 62),
  typographyPreset("editorial", "display_plus_text", "crimson_text", "source_sans_3", 82, 64, 44, 72, 56),
  typographyPreset("editorial", "display_plus_text", "cardo", "work_sans", 80, 64, 46, 70, 54),
  typographyPreset("editorial", "single_family", "eb_garamond", "eb_garamond", 82, 66, 42, 72, 56),
  typographyPreset("editorial", "single_family", "vollkorn", "vollkorn", 78, 66, 46, 68, 50),
  typographyPreset("editorial", "mono_accent", "newsreader", "ibm_plex_mono", 78, 58, 44, 74, 64),
  typographyPreset("mono_tech", "mono_accent", "space_mono", "inter", 60, 48, 58, 74, 68),
  typographyPreset("mono_tech", "mono_accent", "roboto_mono", "source_sans_3", 58, 50, 56, 70, 64),
  typographyPreset("mono_tech", "mono_accent", "source_code_pro", "public_sans", 58, 48, 56, 70, 66),
  typographyPreset("mono_tech", "mono_accent", "commit_mono", "satoshi", 62, 46, 62, 78, 72),
  typographyPreset("mono_tech", "mono_accent", "recursive_mono", "inter", 60, 50, 58, 72, 68),
  typographyPreset("mono_tech", "display_plus_text", "jetbrains_mono", "atkinson_hyperlegible", 60, 48, 62, 70, 68),
  typographyPreset("mono_tech", "single_family", "space_mono", "space_mono", 56, 44, 56, 62, 62),
  typographyPreset("playful", "display_plus_text", "syne", "nunito_sans", 82, 62, 66, 84, 52),
  typographyPreset("playful", "display_plus_text", "clash_display", "rubik", 86, 58, 70, 90, 58),
  typographyPreset("playful", "display_plus_text", "syne", "karla", 88, 62, 54, 92, 54),
  typographyPreset("playful", "display_plus_text", "syne", "rubik", 84, 58, 62, 88, 56),
  typographyPreset("playful", "display_plus_text", "bebas_neue", "open_sans", 86, 56, 64, 92, 60),
  typographyPreset("playful", "single_family", "rubik", "rubik", 76, 66, 64, 64, 34),
  typographyPreset("playful", "single_family", "urbanist", "urbanist", 78, 64, 66, 70, 40),
  typographyPreset("playful", "editorial_contrast", "fraunces", "rubik", 86, 62, 54, 86, 54),
  typographyPreset("playful", "mono_accent", "bebas_neue", "space_mono", 84, 52, 62, 90, 66),
  typographyPreset("luxury", "editorial_contrast", "cormorant_garamond", "manrope", 86, 52, 38, 92, 80),
  typographyPreset("luxury", "editorial_contrast", "libre_baskerville", "satoshi", 82, 56, 40, 84, 70),
  typographyPreset("luxury", "editorial_contrast", "newsreader", "questrial", 80, 58, 42, 80, 66),
  typographyPreset("luxury", "editorial_contrast", "libre_baskerville", "assistant", 78, 58, 42, 76, 62),
  typographyPreset("luxury", "display_plus_text", "playfair_display", "questrial", 84, 54, 40, 88, 76),
  typographyPreset("luxury", "single_family", "cormorant_garamond", "cormorant_garamond", 82, 54, 38, 86, 76),
  typographyPreset("luxury", "single_family", "libre_baskerville", "libre_baskerville", 78, 58, 42, 74, 62),
  typographyPreset("luxury", "mono_accent", "didot", "ibm_plex_mono", 78, 48, 40, 86, 80),
  typographyPreset("geometric", "display_plus_text", "inter", "plus_jakarta_sans", 72, 58, 64, 64, 52),
  typographyPreset("geometric", "display_plus_text", "space_grotesk", "outfit", 78, 56, 68, 76, 58),
  typographyPreset("grotesk", "display_plus_text", "helvetica_neue", "schibsted_grotesk", 70, 60, 62, 62, 48),
  typographyPreset("grotesk", "display_plus_text", "archivo", "archivo", 72, 58, 70, 72, 56),
  typographyPreset("humanist", "display_plus_text", "manrope", "mulish", 66, 72, 50, 50, 30),
  typographyPreset("humanist", "display_plus_text", "raleway", "hind_madurai", 68, 70, 52, 56, 34),
  typographyPreset("editorial", "display_plus_text", "lora", "pt_sans", 80, 64, 46, 72, 54),
  typographyPreset("editorial", "editorial_contrast", "playfair_display", "cardo", 88, 58, 44, 88, 74),
  typographyPreset("mono_tech", "mono_accent", "sf_mono", "cousine", 58, 46, 56, 70, 66),
  typographyPreset("mono_tech", "mono_accent", "jetbrains_mono", "recursive_mono", 60, 46, 62, 76, 70),
  typographyPreset("playful", "display_plus_text", "bebas_neue", "epilogue", 84, 58, 64, 88, 56),
  typographyPreset("playful", "display_plus_text", "bebas_neue", "archivo", 82, 56, 62, 86, 58),
  typographyPreset("luxury", "editorial_contrast", "didot", "libre_caslon_text", 82, 52, 38, 88, 76),
  typographyPreset("luxury", "editorial_contrast", "bodoni_72", "spectral", 80, 54, 40, 84, 70),
  typographyPreset("geometric", "display_plus_text", "onest", "inter", 74, 58, 68, 70, 52),
  typographyPreset("geometric", "single_family", "onest", "onest", 72, 58, 66, 68, 50),
  typographyPreset("geometric", "editorial_contrast", "inria_serif", "onest", 82, 58, 48, 80, 64),
  typographyPreset("grotesk", "display_plus_text", "tahoma", "inter", 68, 62, 58, 54, 46),
  typographyPreset("grotesk", "single_family", "tahoma", "tahoma", 66, 64, 56, 50, 42),
  typographyPreset("humanist", "display_plus_text", "tahoma", "source_sans_3", 64, 70, 52, 48, 32),
  typographyPreset("editorial", "editorial_contrast", "inria_serif", "inter", 86, 56, 44, 86, 72),
  typographyPreset("editorial", "single_family", "inria_serif", "inria_serif", 80, 64, 42, 74, 58),
  typographyPreset("editorial", "display_plus_text", "inria_serif", "source_sans_3", 84, 60, 46, 78, 60),
  typographyPreset("editorial", "editorial_contrast", "shippori_mincho", "public_sans", 88, 58, 42, 88, 74),
  typographyPreset("luxury", "editorial_contrast", "shippori_mincho", "onest", 84, 54, 38, 90, 78),
  typographyPreset("luxury", "single_family", "shippori_mincho", "shippori_mincho", 80, 56, 40, 86, 72),
  typographyPreset("luxury", "display_plus_text", "shippori_mincho", "questrial", 82, 54, 40, 84, 70),
  typographyPreset("geometric", "display_plus_text", "poppins", "instrument_sans", 74, 58, 66, 70, 52),
  typographyPreset("geometric", "single_family", "cooper_hewitt", "cooper_hewitt", 72, 58, 64, 68, 50),
  typographyPreset("geometric", "display_plus_text", "reglo", "public_sans", 76, 56, 68, 72, 54),
  typographyPreset("geometric", "mono_accent", "m_plus_1", "fragment_mono", 70, 52, 64, 72, 62),
  typographyPreset("grotesk", "display_plus_text", "chivo", "overpass", 68, 62, 60, 58, 48),
  typographyPreset("grotesk", "display_plus_text", "open_sauce_sans", "source_sans_3", 66, 64, 58, 52, 46),
  typographyPreset("grotesk", "single_family", "aileron", "aileron", 66, 64, 56, 50, 42),
  typographyPreset("grotesk", "display_plus_text", "tex_gyre_heros", "liberation_sans", 68, 62, 58, 54, 46),
  typographyPreset("grotesk", "display_plus_text", "terminal_grotesque", "gap_sans", 70, 58, 72, 70, 54),
  typographyPreset("grotesk", "display_plus_text", "sporting_grotesque", "chivo", 68, 60, 64, 66, 50),
  typographyPreset("humanist", "display_plus_text", "inclusive_sans", "hauora_sans", 64, 72, 50, 48, 30),
  typographyPreset("humanist", "single_family", "mattone", "mattone", 62, 74, 50, 44, 28),
  typographyPreset("humanist", "display_plus_text", "cotham_sans", "karrik", 66, 70, 52, 50, 32),
  typographyPreset("humanist", "editorial_contrast", "gelasio", "instrument_sans", 76, 66, 46, 66, 52),
  typographyPreset("editorial", "editorial_contrast", "ibm_plex_serif", "public_sans", 86, 56, 44, 86, 72),
  typographyPreset("editorial", "single_family", "young_serif", "young_serif", 80, 64, 42, 74, 58),
  typographyPreset("editorial", "display_plus_text", "bluu_next", "open_sauce_sans", 84, 58, 44, 80, 62),
  typographyPreset("editorial", "editorial_contrast", "libre_moretus", "overpass", 82, 60, 42, 78, 66),
  typographyPreset("luxury", "editorial_contrast", "bagnard", "cooper_hewitt", 82, 54, 38, 86, 74),
  typographyPreset("luxury", "single_family", "minipax", "minipax", 78, 56, 40, 80, 68),
  typographyPreset("luxury", "display_plus_text", "junicode", "league_spartan", 80, 58, 42, 76, 64),
  typographyPreset("playful", "display_plus_text", "ostrich_sans", "rubik", 84, 58, 64, 88, 52),
  typographyPreset("playful", "display_plus_text", "league_gothic", "nunito_sans", 86, 54, 66, 90, 56),
  typographyPreset("playful", "single_family", "violet_sans", "violet_sans", 78, 62, 64, 68, 38),
  typographyPreset("playful", "editorial_contrast", "grenze_gotisch", "nunito", 82, 56, 48, 80, 58),
  typographyPreset("mono_tech", "mono_accent", "office_code_pro", "instrument_sans", 58, 46, 56, 72, 66),
  typographyPreset("mono_tech", "mono_accent", "recursive", "open_sauce_sans", 60, 48, 58, 74, 68),
  typographyPreset("mono_tech", "display_plus_text", "courier_prime", "public_sans", 58, 50, 54, 68, 64),
  typographyPreset("mono_tech", "single_family", "compagnon", "compagnon", 56, 44, 54, 62, 62),
  typographyPreset("luxury", "editorial_contrast", "fdi_wiking", "liberation_sans", 78, 52, 36, 84, 76),
  typographyPreset("geometric", "display_plus_text", "geist_sans", "instrument_sans", 74, 58, 66, 72, 52),
  typographyPreset("geometric", "single_family", "geist_sans", "geist_sans", 72, 58, 64, 70, 50),
  typographyPreset("geometric", "display_plus_text", "tasa_orbiter", "libre_franklin", 76, 56, 62, 74, 54),
  typographyPreset("grotesk", "display_plus_text", "firago", "libre_franklin", 68, 62, 58, 56, 48),
  typographyPreset("grotesk", "display_plus_text", "ibm_plex_sans_condensed", "inria_sans", 66, 64, 60, 54, 46),
  typographyPreset("humanist", "editorial_contrast", "zilla_slab", "inria_sans", 74, 68, 48, 64, 52),
  typographyPreset("editorial", "editorial_contrast", "alegreya", "libre_franklin", 86, 56, 44, 84, 72),
  typographyPreset("editorial", "display_plus_text", "instrument_serif", "geist_sans", 84, 58, 44, 82, 64),
  typographyPreset("editorial", "single_family", "commissioner", "commissioner", 78, 62, 46, 70, 54),
  typographyPreset("editorial", "editorial_contrast", "messapia", "inria_sans", 88, 54, 42, 86, 74),
  typographyPreset("editorial", "display_plus_text", "crimson_pro", "firago", 82, 60, 44, 76, 58),
  typographyPreset("luxury", "display_plus_text", "alegreya", "tasa_orbiter", 84, 54, 40, 80, 68),
  typographyPreset("playful", "display_plus_text", "rakkas", "biorhyme", 86, 58, 54, 88, 52),
  typographyPreset("playful", "display_plus_text", "le_murmure", "fivo_sans", 84, 56, 58, 86, 50),
  typographyPreset("mono_tech", "mono_accent", "monaspace_neon", "geist_sans", 58, 46, 56, 74, 68),
  typographyPreset("mono_tech", "mono_accent", "monaspace_argon", "instrument_sans", 58, 48, 58, 72, 66),
  typographyPreset("mono_tech", "mono_accent", "geist_mono", "public_sans", 56, 46, 56, 70, 64),
  typographyPreset("mono_tech", "single_family", "paper_mono", "paper_mono", 56, 44, 54, 68, 62),
  typographyPreset("mono_tech", "display_plus_text", "monaspace_xenon", "ia_writer_quattro", 58, 46, 56, 72, 68),
  typographyPreset("mono_tech", "mono_accent", "monaspace_krypton", "fivo_sans_modern", 58, 48, 56, 74, 70),
];